image: maven:3.9-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Xss16m -Xms2048m -Xmx16g"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

stages:
  - build

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -Dforce.fast=true
  artifacts:
    paths:
      - target/KorAP-Tokenizer-*-standalone.jar
    expire_in: 1 week
