name: Upload to Zenodo

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish_to_zenodo:
    name: Publish to Zenodo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create new Zenodo version
        uses: zenodraft/action@0.13.3
        with:
          concept: 5040449
          metadata: .zenodo.json
          publish: true
          sandbox: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_TOKEN }}
